/**
 * LogListRow — the auto-log message-list row (Phase 4, Task 9 / deferred Task 4–5
 * log variant).
 *
 * Matches the prototype's `.mi.logrow` (docs/prototypes/ledger-outlook-redesign.html
 * lines 1017–1027): for Correspondence-Log category views the middle-pane rows are
 * `CorrespondenceLogItem`s, not personal mail. They render as:
 *
 *   [ref/source chip] [subject · "Generated by … · for G…" + auto-logged badge] [date · status]
 *
 * The list item ships only the fields the backend's `CorrespondenceLogItem`
 * carries (`source_kind`, `category_id`, `created_by`, `related_employee_id`,
 * `entry_date`). It has NO `ref` or workflow-status field, so — per the plan —
 * we render what's available (a source-kind chip, the generated-by/for line, the
 * auto-logged badge, the date) and omit the status chip rather than fabricate it.
 *
 * The mail row (`MessageListRow`) is unchanged; this is its sibling log variant.
 */

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import type { CorrespondenceLogItem } from '@/lib/api'
import { cn } from '@/lib/utils'

interface LogListRowProps {
  entry: CorrespondenceLogItem
  selected: boolean
  onSelect: (id: number) => void
}

export function LogListRow({ entry, selected, onSelect }: LogListRowProps): React.JSX.Element {
  const { t, i18n } = useTranslation()

  const dateFmt = useMemo(
    () => new Intl.DateTimeFormat(i18n.language, { day: '2-digit', month: 'short' }),
    [i18n.language],
  )
  const dateLabel = useMemo(
    () => dateFmt.format(new Date(`${entry.entry_date}T00:00:00`)),
    [entry.entry_date, dateFmt],
  )

  // The "ref" chip — no ref field on the item, so use the source kind (book /
  // document / …) as the wayfinding chip; fall back to a generic LOG tag.
  const chip = (entry.source_kind ?? 'log').toUpperCase()

  // "Generated by {created_by} · for {related_employee_id}" — render each half
  // only when present.
  const genParts: string[] = []
  if (entry.created_by) genParts.push(`${t('ledger.outlook.logrow.generatedBy')} ${entry.created_by}`)
  if (entry.related_employee_id)
    genParts.push(`${t('ledger.outlook.logrow.forLbl')} ${entry.related_employee_id}`)
  const genLine = genParts.join(' · ')

  return (
    <button
      type="button"
      onClick={() => onSelect(entry.id)}
      aria-current={selected}
      className={cn(
        'grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-start gap-2.5 border-b border-hairline px-3.5 py-2.5 text-start transition-colors last:border-b-0',
        selected ? 'bg-info-soft hover:bg-info-soft' : 'hover:bg-surface-tinted',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-inset',
      )}
    >
      {/* ref / source-kind chip */}
      <span className="mt-px flex-none rounded-[5px] bg-primary-soft px-[7px] py-[3px] font-mono text-[0.66em] font-bold text-primary">
        {chip}
      </span>

      <span className="min-w-0">
        <span className="block truncate text-[0.86em] leading-snug text-foreground" dir="auto">
          {entry.subject}
        </span>
        <span className="mt-[3px] flex flex-wrap items-center gap-1.5">
          {genLine && (
            <span className="min-w-0 truncate text-[0.72em] text-faint" dir="auto">
              {genLine}
            </span>
          )}
          <span className="flex-none rounded-full bg-success-soft px-[7px] py-px text-[0.56em] font-bold uppercase tracking-wide text-success">
            {t('ledger.outlook.logrow.autoLogged')}
          </span>
        </span>
      </span>

      <span className="flex flex-col items-end gap-1 rtl:items-start">
        <span className="whitespace-nowrap text-[0.72em] text-faint">{dateLabel}</span>
      </span>
    </button>
  )
}
