/**
 * LogRecordView — read-only record card rendered into the ReadingPaneSlot when a
 * Correspondence-Log row is selected (Phase 5, Task 6).
 *
 * Fetches `getLedgerLogRecord(recordId)` → `CorrespondenceLogRecord` and renders:
 *   • rp-top header: ref/source chip + auto-logged badge + subject; status badge +
 *     date in rp-actions (matching prototype `renderRecord` lines 1066–1092).
 *   • rec-grid rows: Reference · Subject · Generated by · Linked employee(s) ·
 *     Category · Status — only fields that exist on `CorrespondenceLogRecord`.
 *
 * No reply UI, no recipients, no compose. Loading + not-found states.
 *
 * Prototype reference: `renderRecord` (ledger-outlook-redesign.html lines 1066–1092)
 * i18n keys: `ledger.outlook.record.*` (added in this task).
 */

import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'

import { api } from '@/lib/api'
import type { CorrespondenceLogRecord } from '@/lib/api'

interface LogRecordViewProps {
  recordId: number
}

/** Map `book_approval_state` to a display colour class + label. */
function statusInfo(
  state: string | null | undefined,
  tSigned: string,
  tAwaiting: string,
): { label: string; cls: string } {
  if (state === 'signed') return { label: tSigned, cls: 'text-success-foreground bg-success-soft border-success-soft' }
  return { label: tAwaiting, cls: 'text-amber-700 bg-amber-50 border-amber-200' }
}

export function LogRecordView({ recordId }: LogRecordViewProps): React.JSX.Element {
  const { t, i18n } = useTranslation()
  const isAr = i18n.language.startsWith('ar')

  const query = useQuery({
    queryKey: ['ledger-log-record', recordId],
    queryFn: () => api.getLedgerLogRecord(recordId),
  })

  if (query.isLoading) {
    return (
      <RecordShell ariaLabel={t('ledger.outlook.record.loading')}>
        <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground p-10">
          {t('ledger.outlook.record.loading')}
        </div>
      </RecordShell>
    )
  }

  const rec: CorrespondenceLogRecord | undefined = query.data

  if (!rec) {
    return (
      <RecordShell ariaLabel={t('ledger.outlook.record.notFound')}>
        <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground p-10">
          {t('ledger.outlook.record.notFound')}
        </div>
      </RecordShell>
    )
  }

  const formattedDate = new Date(rec.entry_date).toLocaleDateString(
    isAr ? 'ar-AE' : undefined,
    { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' },
  )

  const tSigned = t('ledger.outlook.record.signed')
  const tAwaiting = t('ledger.outlook.record.awaiting')
  const status = statusInfo(rec.book_approval_state, tSigned, tAwaiting)

  // Reference to display: book ref number when present, else source_kind
  const refDisplay = rec.book_ref_number ?? rec.source_kind ?? '—'

  // Category label: prefer language-matched name
  const categoryLabel =
    (isAr ? rec.category_name_ar : rec.category_name_en) ??
    rec.category_key ??
    null

  return (
    <RecordShell ariaLabel={rec.subject}>
      <div className="flex flex-1 flex-col overflow-y-auto">
        {/* ── rp-top: ref chip + badge + subject | status badge + date ── */}
        <div className="flex items-start justify-between gap-4 border-b border-hairline px-6 py-4">
          <div className="min-w-0">
            <div className="mb-[7px] flex flex-wrap items-center gap-2">
              {/* ref chip */}
              <span className="inline-flex items-center rounded border border-border-strong bg-surface-raised px-2 py-0.5 font-mono text-[11px] text-foreground">
                {refDisplay}
              </span>
              {/* auto-logged badge */}
              <span className="inline-flex items-center rounded border border-info/30 bg-info/10 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-info">
                {t('ledger.outlook.logrow.autoLogged')}
              </span>
            </div>
            <h1
              className="text-xl font-bold leading-snug tracking-tight text-foreground"
              dir="auto"
            >
              {rec.subject}
            </h1>
          </div>
          {/* status badge + date */}
          <div className="flex flex-none flex-col items-end gap-1.5 rtl:items-start">
            <span
              className={`inline-flex items-center rounded border px-2 py-0.5 text-[11px] font-semibold ${status.cls}`}
            >
              {status.label}
            </span>
            <div className="text-xs text-faint">{formattedDate}</div>
          </div>
        </div>

        {/* ── rec-grid: label / value rows ── */}
        <div className="px-6 py-4">
          <dl className="grid gap-y-3">
            {/* Reference */}
            <RecRow label={t('ledger.outlook.record.ref')}>
              <span className="font-mono text-sm">{refDisplay}</span>
            </RecRow>

            {/* Subject */}
            <RecRow label={t('ledger.outlook.record.subject')}>
              <span dir="auto">{rec.subject}</span>
            </RecRow>

            {/* Generated by */}
            {rec.created_by && (
              <RecRow label={t('ledger.outlook.record.generatedBy')}>
                <span dir="auto">{rec.created_by}</span>
              </RecRow>
            )}

            {/* Linked employee(s) */}
            <RecRow label={t('ledger.outlook.record.linkedEmployee')}>
              {rec.related_employee_id ? (
                <span className="inline-flex items-center rounded border border-border-strong bg-surface-raised px-2 py-0.5 font-mono text-xs text-foreground">
                  {rec.related_employee_id}
                </span>
              ) : (
                <span className="text-faint">—</span>
              )}
            </RecRow>

            {/* Category — only when resolved */}
            {categoryLabel && (
              <RecRow label={t('ledger.outlook.record.category')}>
                <span>{categoryLabel}</span>
              </RecRow>
            )}

            {/* Status */}
            <RecRow label={t('ledger.outlook.record.status')}>
              <span
                className={`inline-flex items-center rounded border px-2 py-0.5 text-[11px] font-semibold ${status.cls}`}
              >
                {status.label}
              </span>
            </RecRow>
          </dl>
        </div>
      </div>
    </RecordShell>
  )
}

/** Outer shell — mirror of ReadingPane's PaneShell. */
function RecordShell({
  children,
  ariaLabel,
}: {
  children: React.ReactNode
  ariaLabel: string
}): React.JSX.Element {
  return (
    <div
      className="flex min-w-0 flex-1 flex-col overflow-hidden bg-surface"
      role="region"
      aria-label={ariaLabel}
    >
      {children}
    </div>
  )
}

/** One label+value row in the rec-grid. */
function RecRow({
  label,
  children,
}: {
  label: string
  children: React.ReactNode
}): React.JSX.Element {
  return (
    <div className="flex flex-col gap-0.5 sm:flex-row sm:gap-4">
      <dt className="w-36 flex-none text-xs font-semibold text-muted-foreground sm:text-right rtl:sm:text-left">
        {label}
      </dt>
      <dd className="min-w-0 text-sm text-foreground">{children}</dd>
    </div>
  )
}
