<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Gssg.Outlook.Launcher</RootNamespace>
    <AssemblyName>Gssg.Outlook.Launcher</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gssg.Outlook.Shared\Gssg.Outlook.Shared.csproj" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="Microsoft.Office.Interop.Outlook">
      <Guid>{00062FFF-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>9</VersionMajor>
      <VersionMinor>6</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
</Project>
