"""Ledger→Outlook Phase 3: automated Correspondence Log.

Revision ID: 0032_correspondence_log
Revises: 0031_address_book_contacts
Create Date: 2026-06-07

New tables:
  correspondence_categories — bilingual document-type buckets (HR letters,
    Salary/bank, Leaves, Government/NAT, Incoming stamped). UNIQUE(key).
  correspondence_rules — admin-editable "When [trigger] [condition] -> file as
    [category]"; FK category_id -> correspondence_categories (both new tables).

ledger_entries:
  + source_kind STR(32) NULL (e.g. 'generated_doc' / 'intake_scan'), indexed
  + category_id INT NULL (FK omitted — ALTER on existing table; app-side
    integrity, mirrors owner_user_id), indexed

Seeds the 5 default categories + the default rules ON (document_generated by
category -> HR letters / Salary-bank / Leaves / Gov-NAT; intake_classified
incoming -> Incoming stamped). The email_sent rule is seeded OFF per the mockup.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0032_correspondence_log"
down_revision: str | Sequence[str] | None = "0031_address_book_contacts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# (key, name_en, name_ar, sort)
_CATEGORIES: tuple[tuple[str, str, str, int], ...] = (
    ("hr_letters", "HR letters", "خطابات الموارد البشرية", 10),
    ("salary_bank", "Salary / bank", "الرواتب / البنك", 20),
    ("leaves", "Leaves", "الإجازات", 30),
    ("gov_nat", "Government / NAT", "حكومي / الخدمة الوطنية", 40),
    ("incoming_stamped", "Incoming (stamped)", "وارد (مختوم)", 50),
)

# (trigger, condition_json, category_key, enabled, sort)
_RULES: tuple[tuple[str, str, str, int, int], ...] = (
    ("document_generated", '{"category": "HR"}', "hr_letters", 1, 10),
    ("document_generated", '{"category": "NAT"}', "gov_nat", 1, 20),
    ("intake_classified", '{"kind": "incoming"}', "incoming_stamped", 1, 30),
    # email_sent ships OFF (admin may enable in the rules UI).
    ("email_sent", "{}", "hr_letters", 0, 40),
)


def upgrade() -> None:
    op.create_table(
        "correspondence_categories",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("key", sa.String(64), nullable=False),
        sa.Column("name_en", sa.String(128), nullable=False, server_default=""),
        sa.Column("name_ar", sa.String(128), nullable=False, server_default=""),
        sa.Column("sort", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("system", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("key", name="uq_correspondence_categories_key"),
    )
    op.create_table(
        "correspondence_rules",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("trigger", sa.String(32), nullable=False),
        sa.Column("condition_json", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column(
            "category_id",
            sa.Integer(),
            sa.ForeignKey("correspondence_categories.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("sort", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index(
        "ix_correspondence_rules_trigger", "correspondence_rules", ["trigger"]
    )

    with op.batch_alter_table("ledger_entries") as batch:
        batch.add_column(sa.Column("source_kind", sa.String(32), nullable=True))
        batch.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch.create_index("ix_ledger_entries_source_kind", ["source_kind"])
        batch.create_index("ix_ledger_entries_category_id", ["category_id"])

    # ── Seed default categories + rules (system=1 so they're protected). ──
    conn = op.get_bind()
    for key, en, ar, sort in _CATEGORIES:
        conn.execute(
            sa.text(
                "INSERT INTO correspondence_categories "
                "(key, name_en, name_ar, sort, system, created_at) "
                "VALUES (:key, :en, :ar, :sort, 1, CURRENT_TIMESTAMP)"
            ),
            {"key": key, "en": en, "ar": ar, "sort": sort},
        )
    cat_id_by_key = {
        r._mapping["key"]: r._mapping["id"]
        for r in conn.execute(
            sa.text("SELECT id, key FROM correspondence_categories")
        )
    }
    for trigger, cond, cat_key, enabled, sort in _RULES:
        conn.execute(
            sa.text(
                "INSERT INTO correspondence_rules "
                "(trigger, condition_json, category_id, enabled, sort, created_at) "
                "VALUES (:trigger, :cond, :cat_id, :enabled, :sort, CURRENT_TIMESTAMP)"
            ),
            {
                "trigger": trigger,
                "cond": cond,
                "cat_id": cat_id_by_key[cat_key],
                "enabled": enabled,
                "sort": sort,
            },
        )


def downgrade() -> None:
    with op.batch_alter_table("ledger_entries") as batch:
        batch.drop_index("ix_ledger_entries_category_id")
        batch.drop_index("ix_ledger_entries_source_kind")
        batch.drop_column("category_id")
        batch.drop_column("source_kind")
    op.drop_index("ix_correspondence_rules_trigger", table_name="correspondence_rules")
    op.drop_table("correspondence_rules")
    op.drop_table("correspondence_categories")
